# Generated by Django 5.0.1 on 2024-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviosClientes',
            fields=[
                ('idenvio', models.IntegerField(primary_key=True, serialize=False)),
                ('direccionenvio', models.CharField(max_length=100)),
                ('idtecnico', models.IntegerField()),
                ('nombreestadoenvio', models.CharField(max_length=100)),
                ('idcliente', models.IntegerField()),
                ('direccioncliente', models.CharField(max_length=100)),
                ('documentocliente', models.IntegerField()),
            ],
            options={
                'db_table': 'vistaenviosclientes',
                'managed': False,
            },
        ),
    ]
