# Generated by Django 5.0.1 on 2024-03-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_enviosclientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadTecnicos',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Especialidad_tecnicos',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='detalleenviosventas',
            table='detalle_envios_y_ventas',
        ),
        migrations.AlterModelTable(
            name='tecnicos',
            table='Tecnicos',
        ),
    ]
