# Generated by Django 5.0.1 on 2024-03-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_especialidadtecnicos_alter_detalleenviosventas_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividadescronogramatecnicos',
        ),
        migrations.DeleteModel(
            name='Detallesactividadcronograma',
        ),
    ]
